ForumTable: 
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Forum
    AttributeDefinitions:
    -
      AttributeName: Name
      AttributeType: S
    -
      AttributeName: Group
      AttributeType: S
    KeySchema:
    -
      AttributeName: Name
      KeyType: HASH
    -
      AttributeName: Group
      KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

ThreadTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Thread
    AttributeDefinitions:
    -
      AttributeName: ForumName
      AttributeType: S
    - 
      AttributeName: Subject
      AttributeType: S
    KeySchema:
    -
      AttributeName: ForumName
      KeyType: HASH
    -
      AttributeName: Subject
      KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

ReplyTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Reply
    AttributeDefinitions:
    -
      AttributeName: Id
      AttributeType: S
    -
      AttributeName: Subject
      AttributeType: S
    KeySchema:
    -
      AttributeName: Id
      KeyType: HASH
    -
      AttributeName: Subject
      KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5